spring.port=8082
spring.application.name=PRODUCT-SERVICE
spring.profiles.active=dev
spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/productdb}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true

logging.level.com.tnf.product_service=DEBUG
logging.level.org.springframework.cloud.sleuth=DEBUG

management.endpoints.web.exposure.include=health,info,metrics,beans,httptrace,gateway,prometheus
management.endpoint.health.show-details=always
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.propagation.type=b3
management.zipkin.tracing.endpoint=${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

info.app.name=Product Service
info.app.version=1.0.0
info.app.description=Manages Product catalog
springdoc.api-docs.path=/v3/api-docs